# Generated by Django 2.2 on 2019-05-03 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='awayTeam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awayTeam_set', to='teams.Team'),
        ),
        migrations.AlterField(
            model_name='game',
            name='homeTeam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeTeam_set', to='teams.Team'),
        ),
    ]
